### ISSUE TITLE
Link checker failing

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/cmip6-cookbook#45]
The nightly build is currently [failing because of the link checker](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/4400554198/jobs/7705959378). There are 403 (Forbidden) errors for links to a few papers, which are all AGU publications.

**Comment by brian-rose** [comment]
High priority but will be solved upstream with https://github.com/ProjectPythia/cookbook-actions/issues/60

**Comment by brian-rose** [comment]
Actually in https://github.com/ProjectPythia/cookbook-actions/issues/60 I decided to implement the solution at the individual cookbook repo level so I'll open a new PR here.
