### ISSUE TITLE
Need Henri Drake's ORCID

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/cmip6-cookbook#59]
We now have a CITATION.cff file for author attribution. It would be great to add an ORCID (and maybe other metadata) for  @hdrake.

Henri, if you see this, please feel free to open a PR to add your details.

**Comment by hdrake** [comment]
Thanks @brian-rose! https://github.com/ProjectPythia/cmip6-cookbook/pull/60 closes this issue.
