### ISSUE TITLE
Binderbot building from different repo

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/cmip6-cookbook#71]
The binder seems to be pointing to [`mgrover1/cmip6-cookbook`](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/6620830967/job/17983905055#step:18:46) instead of `ProjectPythia/cmip6-cookbook`, and after that change, the nightly build has been consistently failing. @mgrover1, is this an issue? I can't find where that change was made.

**Comment by brian-rose** [comment]
@r-ford is this related to the current failures (May 2024)?
