### ISSUE TITLE
Nightly builds failing for a long while

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/cmip6-cookbook#86]
**What happened**:

Dear authors and/or contributors (cc'ing @r-ford and @mgrover1 as you have the two largest contributions), the nightly builds of this cookbook have been failing for the last several months. 

Could you please have a look at it?

**Minimal Complete Verifiable Example**:

[Latest nightly build](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/11376131517/job/31648091967) as of the creation of this issue.

**Anything else we need to know?**:

If you think it is due to Pythia infrastructure or something else other than the cookbook itself, please let us know.

**Comment by r-ford** [comment]
Fixed with #87
